// <auto-generated />
using System;
using CSC237_JFink_Final2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSC237_JFink_Final2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190415035156_GolferSeedData1")]
    partial class GolferSeedData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSC237_JFink_Final2.Models.Distance", b =>
                {
                    b.Property<int>("distanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("attackWedgeDistance");

                    b.Property<double>("driverDistance");

                    b.Property<double>("eightIronDistance");

                    b.Property<double>("fiveIronDistance");

                    b.Property<double>("fiveWoodDistance");

                    b.Property<double>("fourIronDistance");

                    b.Property<double>("nineIronDistance");

                    b.Property<double>("pitchingWedgeDistance");

                    b.Property<double>("sandWedgeDistance");

                    b.Property<double>("sevenIronDistance");

                    b.Property<double>("sixIronDistance");

                    b.Property<double>("threeWoodDistance");

                    b.HasKey("distanceId");

                    b.ToTable("Distances");
                });

            modelBuilder.Entity("CSC237_JFink_Final2.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("MemberID");

                    b.ToTable("Members");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Member");
                });

            modelBuilder.Entity("CSC237_JFink_Final2.Models.Scores", b =>
                {
                    b.Property<int>("scoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("backNineScore");

                    b.Property<int>("frontNineScore");

                    b.Property<int>("numBirdies");

                    b.Property<int>("numBogeys");

                    b.Property<int>("numDoubleBogeys");

                    b.Property<int>("numEagles");

                    b.Property<int>("numPars");

                    b.Property<int>("totalPutts");

                    b.Property<int>("totalScore");

                    b.HasKey("scoreId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("CSC237_JFink_Final2.Models.Golfer", b =>
                {
                    b.HasBaseType("CSC237_JFink_Final2.Models.Member");

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<double>("Handicap");

                    b.Property<int?>("LeagueManagerMemberID");

                    b.Property<int?>("myDistancedistanceId");

                    b.Property<int?>("myScoresscoreId");

                    b.HasIndex("LeagueManagerMemberID");

                    b.HasIndex("myDistancedistanceId");

                    b.HasIndex("myScoresscoreId");

                    b.ToTable("Golfer");

                    b.HasDiscriminator().HasValue("Golfer");

                    b.HasData(
                        new { MemberID = 1, Email = "dakrlonz@hotmail.com", FirstName = "Justin", LastName = "Fink", Password = "123", Username = "Finklacon", Age = 29, Gender = "Male", Handicap = 18.8 },
                        new { MemberID = 2, Email = "@.com", FirstName = "Kyle", LastName = "Marley", Password = "123", Username = "Marley", Age = 33, Gender = "Male", Handicap = 11.0 },
                        new { MemberID = 3, Email = "@.com", FirstName = "Scott", LastName = "Smith", Password = "123", Username = "Smith", Age = 24, Gender = "Male", Handicap = 21.0 },
                        new { MemberID = 4, Email = "@.com", FirstName = "Ramon", LastName = "Casias", Password = "123", Username = "Casias", Age = 31, Gender = "Male", Handicap = 25.8 },
                        new { MemberID = 5, Email = "@.com", FirstName = "William", LastName = "Dietz", Password = "123", Username = "Dietz", Age = 30, Gender = "Male", Handicap = 1.8 }
                    );
                });

            modelBuilder.Entity("CSC237_JFink_Final2.Models.LeagueManager", b =>
                {
                    b.HasBaseType("CSC237_JFink_Final2.Models.Member");

                    b.Property<int>("LeagueManagerID");

                    b.Property<int>("NumOfTeams");

                    b.ToTable("LeagueManager");

                    b.HasDiscriminator().HasValue("LeagueManager");
                });

            modelBuilder.Entity("CSC237_JFink_Final2.Models.Golfer", b =>
                {
                    b.HasOne("CSC237_JFink_Final2.Models.LeagueManager")
                        .WithMany("golfers")
                        .HasForeignKey("LeagueManagerMemberID");

                    b.HasOne("CSC237_JFink_Final2.Models.Distance", "myDistance")
                        .WithMany()
                        .HasForeignKey("myDistancedistanceId");

                    b.HasOne("CSC237_JFink_Final2.Models.Scores", "myScores")
                        .WithMany()
                        .HasForeignKey("myScoresscoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
